name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'

          # Sesuaikan dengan direktori proyek dan URL repositori Anda
          PROJECT_DIR="F-BEE24001186-km7-ali-banksystem-ch2"
          REPO_URL="https://github.com/alifaaziz/F-BEE24001186-km7-ali-banksystem-ch2.git"

          # Hapus folder proyek lama jika ada
          if [ -d "$PROJECT_DIR" ]; then
            rm -rf "$PROJECT_DIR"
          fi

          # Kloning ulang repositori
          git clone $REPO_URL "$PROJECT_DIR"
          cd "$PROJECT_DIR"

          # Pastikan berada di cabang main dan tarik pembaruan terbaru
          git checkout main
          git pull origin main

          # Install dependencies
          npm install                

          # Generate Prisma client
          npx prisma generate 

          # Restart atau start PM2 process
          pm2 restart "Bank System Binar" || pm2 start index.js --name "Bank System Binar"
          
          # Simpan konfigurasi PM2 dan setup startup
          pm2 save              
          pm2 startup -u ubuntu --hp /home/ubuntu 
          EOF